server:
  port: 8987

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pruebaFrutasDB
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
