server:
  port: 8987

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://frutas_db:5432/pruebaFrutasDB}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
