server:
  port: 8987

spring:
  datasource:

    url: jdbc:postgresql://dpg-cs9btpij1k6c73fljpk0-a:5432/pruebafrutasdb
    username: post
    password: ykCIHJPvPu3AWtWN60TK1K2v1uhLMoMl

    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
